DEFAULTS: &DEFAULTS
  adapter: mysql
  encoding: utf8
#  host: mysql.pragtech.co.in
#  username: pragmatic_paco
#  password: global786
  host: localhost
  username: root
  password: root
  #socket: /var/run/mysqld/mysqld.sock

development:
  database: gallery_development
  <<: *DEFAULTS

test:
  database: gallery_development
  <<: *DEFAULTS

production:
  database: gallery_development
  <<: *DEFAULTS


