DEFAULTS: &DEFAULTS
  adapter: mysql
  encoding: utf8
#  host: mysql.pragtech.co.in
#  username: pragmatic_paco
#  password: global786
  host: localhost
  username: root
  password: root
  # JRuby doesn't support # JRuby doesn't support # JRuby doesn't support socket:
                                                  #socket:
                          ## JRuby doesn't support socket:
                           #socket:
  # JRuby doesn't support # JRuby doesn't support socket:
                          #socket:
  #host: 127.0.0.1
  ## JRuby doesn't support socket:
   #socket: /var/run/mysqld/mysqld.sock

development:
  database: gallery_development
  <<: *DEFAULTS

test:
  database: gallery_test
  <<: *DEFAULTS

production:
  database: gallery
  <<: *DEFAULTS


