DEFAULTS: &DEFAULTS
  development:
  adapter: mysql
  encoding: utf8
#  host: mysql.pragtech.co.in
#  username: pragmatic_paco
#  password: global786
  host: localhost
  username: root
  password: global

development:
  database: gallery
  <<: *DEFAULTS

test:
  database: gallery_test
  <<: *DEFAULTS

production:
  database: gallery
  <<: *DEFAULTS


